server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        expires -1;
    }

    location = /flutter_bootstrap.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        expires -1;
    }

    location = /main.dart.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        expires -1;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
